name: Create Bucket

on: [push]

jobs:
    testing-action:
        runs-on: ubuntu-latest
        steps:
            # checkout code
            - use: action/checkout@v3

            # setup node (typescript)
            #- use: actions/setup-node@v3.5
            #  with:
            #    node-version: 16

            # auth GCP
            - name: "auth GCP"
              uses: "google-github-actions/auth@v1"
              with:
                credentials_json: "${{ secrets.GCP_TOKEN }}"

            # setup gcloud cli
            - name: "setup GCP"
              uses: "google-github-actions/setup-gcloud@v1"

            # pulumi
            - name: "exec pulumi"
              uses:  pulumi/actions@v4
              with:
                command: preview
                stack-name: dev
              env:
                PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}